// <auto-generated />
using System;
using CareConnect.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareConnect.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725184813_RelacaoUtenteCuidador")]
    partial class RelacaoUtenteCuidador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareConnect.Shared.Models.CarePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("HoraProgramada")
                        .HasColumnType("interval");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("CarePlans");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alergias")
                        .HasColumnType("text");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CondicoesMedicas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contacto")
                        .HasColumnType("text");

                    b.Property<string>("ContactoEmergencia")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GestorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GestorId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.TaskLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarePlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdHoc")
                        .HasColumnType("boolean");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimestampExecucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TituloAdHoc")
                        .HasColumnType("text");

                    b.Property<Guid?>("UtenteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarePlanId");

                    b.HasIndex("ExecutorId");

                    b.ToTable("TaskLogs");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.CarePlan", b =>
                {
                    b.HasOne("CareConnect.Shared.Models.Patient", "Patient")
                        .WithMany("CarePlans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.Patient", b =>
                {
                    b.HasOne("CareConnect.Shared.Models.User", "Gestor")
                        .WithMany("PacientesGeridos")
                        .HasForeignKey("GestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.TaskLog", b =>
                {
                    b.HasOne("CareConnect.Shared.Models.CarePlan", "CarePlan")
                        .WithMany("TaskLogs")
                        .HasForeignKey("CarePlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CareConnect.Shared.Models.User", "Executor")
                        .WithMany("TarefasExecutadas")
                        .HasForeignKey("ExecutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarePlan");

                    b.Navigation("Executor");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.User", b =>
                {
                    b.HasOne("CareConnect.Shared.Models.Patient", null)
                        .WithMany("Cuidadores")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.CarePlan", b =>
                {
                    b.Navigation("TaskLogs");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.Patient", b =>
                {
                    b.Navigation("CarePlans");

                    b.Navigation("Cuidadores");
                });

            modelBuilder.Entity("CareConnect.Shared.Models.User", b =>
                {
                    b.Navigation("PacientesGeridos");

                    b.Navigation("TarefasExecutadas");
                });
#pragma warning restore 612, 618
        }
    }
}
